### ISSUE TITLE
There is nowwhere a function  mb_orig_strlen

### ISSUE THREAD

**Issue by grzchr15** [piwik/component-network#5]
There is nowwhere a function  mb_orig_strlen

/**
     * Returns true if this is an IPv4, IPv4-compat, or IPv4-mapped address, false otherwise.
     *
     * @param string $binaryIp
     * @return bool
     */
    private static function isIPv4($binaryIp)
    {
        // in case mbstring overloads strlen function
        $strlen = function_exists('mb_orig_strlen') ? 'mb_orig_strlen' : 'strlen';

        return $strlen($binaryIp) == 4;
    }

**Comment by mneudert** [comment]
There actually is!

Once you activate the [mbstring function overloading](http://php.net/manual/en/mbstring.overload.php) they get registered. What is missing in the documentation is that all the overloaded functions are still available as `mb_orig_*`. They are probably not what you want to use when using overloading but when handling binary data they are your only option besides deactivating that from PHP 7.2 on deprecated feature.

For reference some PHP source:

- https://github.com/php/php-src/blob/PHP-5.6/ext/mbstring/mbstring.c#L194
- https://github.com/php/php-src/blob/PHP-5.6/ext/mbstring/mbstring.c#L1610

(used `5.6` for the line numbers, but available for everything from `5.0` to `7.2`)

**Comment by mattab** [comment]
Thanks @mneudert for your answer
